### ISSUE TITLE
Revisión y análisis de modelo catalogo para la nueva jerarquía del sistemas, hasta nivel de clase 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/catalogo_elementos_crud#35]
Se debe realizar un análisis del modelo de [datos](https://user-images.githubusercontent.com/23342808/68551355-22cf8280-03da-11ea-8c25-4cb053a1513b.png) para realizar el registro de la nueva jerarquía del catalogo, se debe crear el grupo, segmento, familia, clase, la issue debe cumplir los siguientes requerimientos:

- [x] Analizar si el modelo soporta la nueva jerarquía establecida hasta el nivel 4 

- [x] Realizar un prueba en el api para crear la jerarquía, colocar en un comentario el json final de la creación

**Comment by CristianDavidSanchez** [comment]
Se define en conjunto con el lider técnico que se debe crear una tabla de parametrización en el dbm. se procede a hacer el debido ajuste.

**Comment by CristianDavidSanchez** [comment]
Se genera la tabla de parametrización(tabla jerarquia) y la versión 2 de la base de datos catalogo_elementos se adjunta link de drive con los archivos de las 2 versiones.
Se actualiza el nombre de la pk_tipo_bien para cumplir con lineamiento.
https://drive.google.com/drive/folders/1fLnmPrFI3TCbHqcegAkjr42UDgJOGpZy?usp=sharing

**Comment by CristianDavidSanchez** [comment]
Se genera el cambio de nombre de la tabla, funcional en el api localmente, se realizan los inserts de las clasificaciones a usar en la tabla, se presenta el json obtenido.  
![image](https://user-images.githubusercontent.com/45292213/99698613-fe7f9a80-2a5e-11eb-984b-c9436d6e4086.png)

**Comment by fabianbarreto02** [comment]
Se revisa los ajustes solicitados a nivel de modelo de datos y api

**Comment by fabianbarreto02** [comment]
comentario de prueba

**Comment by fabianbarreto02** [comment]
Se da por finalizado la issue se actualiza en rama develop , no se despliega en prueba por auditoria
