### ISSUE TITLE
Realizar ajuste de modelo y api para manejar la la relaciones de los niveles de jerarquia

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/catalogo_elementos_crud#39]
Se debe realizar los ajustes a nivel de modelo de datos y api para la creación de un tabla que guarde la relación de los niveles de jerarquía, la issue debe cumplir los siguientes requerimientos:

- [x] Ajustar modelo de datos y realizar la documentación

- [x] Ajustar el api con los controladores y modelos

- [x] Ajustar el migrations 

- [x] Realizar prueba de escritorio

**Comment by CristianDavidSanchez** [comment]
Se da inicio al issue

**Comment by CristianDavidSanchez** [comment]
Se genera la tabla que almacenara las relaciones de tipo_nivel, junto con la documentación necesaria para sus cambios. Dejó adjunto el link del drive de la V3 de la base de datos catalogo_elementos y la imagen del esquema.
https://drive.google.com/drive/folders/1fLnmPrFI3TCbHqcegAkjr42UDgJOGpZy?usp=sharing
![image](https://user-images.githubusercontent.com/45292213/99829114-e032a100-2b29-11eb-9b99-020320980d00.png)

**Comment by CristianDavidSanchez** [comment]
Pendiente por pruebas de escritorio.

**Comment by CristianDavidSanchez** [comment]
se realizó el pull y ya esta disponible en develop

**Comment by fabianbarreto02** [comment]
Se realiza el pull requesta develop y se da por finalizada la issue
