### ISSUE TITLE
Agregar parametro para solamente traer una "rama" de un (arbol) catálogo

### ISSUE THREAD

**Issue by AlexFBP** [udistrital/catalogo_elementos_crud#78]
Continúa lo desarrollado en
- https://github.com/udistrital/arka_cliente/issues/649

Actualmente al traer un catalogo (controlador tr_catalogo?) se está trayendo todo, lo cual es un inconveniente cuando un catalogo es grande, como el de [Colombia Compra Eficiente (CCE)](https://colombiacompra.gov.co/clasificador-de-bienes-y-Servicios)
- [x] Identificar el controlador en que se trae el catalogo (posiblemente es `tr_catalogo`) y los ajustes que hay que hacer para:...
- [x] Agregar uno o más parámetros en relación a la rama específica (uno: el subgrupo_id. Dos: catalogo_id Y subgrupo_id)
- [x] Agregar un parámetro para especificar-la-profundidad/limitar-el-nivel-de-recursividad, el equivalente al `limit=`, podría ser `depth=`, donde el valor por defecto podría ser -1 y significaría el comportamiento actual (traer todo). Un 0 podría traer solamente el subgrupo, un 1 podría traer los hijos, un 2 los nietos y así...

Relacionado con
- https://github.com/udistrital/administrativa_cliente/issues/495#issuecomment-893779491

**Comment by ludwinggsanchez** [comment]
Dado que el árbol de nebular no permite que se cambie progresivamente al datasource, se debe migrar al [árbol de material](https://v7.material.angular.io/components/tree/overview)

**Comment by ludwinggsanchez** [comment]
Se construye controlador que retorna un nivel cada vez, el primer nivel pueden ser todos los grupos de un catálogo o un subgrupo particular. El swagger queda como en la imagen:

![image](https://user-images.githubusercontent.com/35748918/134021410-d33ce73a-5482-45f2-9221-3c4badc284b9.png)

**Comment by AlexFBP** [comment]
Se cierra de acuerdo al historial
