### ISSUE TITLE
Ajustar Modelo Catalogo

### ISSUE THREAD

**Issue by AlexFBP** [udistrital/catalogo_elementos_crud#84]
Necesario para las HUs 32 y 33

HU 32 crear un tipo de bien

Puntos: 10

- [x] Ajustar modelo: A `tipo_bien`, agregarle columnas: tipo_bien_padre (no olvidar el constraint...) y reglas: jsonb
- [x] Implementar la interfaz para los tipos de bienes (esto va de la mano con los mockups de parametrizacion de Cristian)

HU 33 consultar tipo de bien

Puntos: 5

Referencias:
- https://github.com/udistrital/administrativa_cliente/projects/1
- [Lineamientos modelo de datos](https://github.com/udistrital/lineamientos_oas/blob/master/modelo_de_datos/estandar.md)

**Comment by CristianDavidSanchez** [comment]
![cambios ca modelo de catalogos](https://user-images.githubusercontent.com/45292213/135665833-2b12fa69-4f52-4c1e-9d4c-785a56828932.png)
Cambios a espera de aprobación
@AlexFBP

**Comment by AlexFBP** [comment]
De mi parte lo veo bien, el objetivo es que, donde aplique, se pueda especificar una jerarquía de tipos de bien, qué opinas @corio27 ?

**Comment by AlexFBP** [comment]
Se cierra de acuerdo al historial
